# Generated by Django 4.1.6 on 2023-04-05 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_remove_category_groups'),
        ('group', '0010_remove_group_users_alter_group_categories'),
        ('users', '0007_user_city_user_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='joined_users', to='category.category'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='joined_users', to='group.group'),
        ),
    ]
