# Generated by Django 4.1.5 on 2023-02-20 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_remove_category_city'),
        ('group', '0002_group_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='category',
            field=models.ManyToManyField(to='category.category'),
        ),
    ]
