# Generated by Django 4.1.5 on 2023-02-20 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_group_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='category',
            new_name='categories',
        ),
    ]
