# Generated by Django 4.1.6 on 2023-02-23 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_alter_group_createdat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='groupName',
            new_name='group_name',
        ),
    ]
