# Generated by Django 4.1.6 on 2023-02-27 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_createdat_user_created_at_and_more'),
        ('group', '0008_rename_createdat_group_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(blank=True, to='users.user'),
        ),
    ]
