# Generated by Django 4.1.6 on 2023-04-05 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_remove_category_groups'),
        ('group', '0009_alter_group_created_at_alter_group_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='users',
        ),
        migrations.AlterField(
            model_name='group',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='joined_groups', to='category.category'),
        ),
    ]
