# Generated by Django 4.1.6 on 2023-04-24 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='details',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='report',
        ),
    ]
