# Generated by Django 4.1.5 on 2023-02-20 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_rename_category_group_categories'),
        ('category', '0002_remove_category_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='groups',
            field=models.ManyToManyField(to='group.group'),
        ),
    ]
