# Generated by Django 4.1.6 on 2023-02-20 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='createdAt',
            field=models.DateField(blank=True, default='2022-10-10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='image',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='group',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
