# Generated by Django 4.1.6 on 2023-02-06 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=30)),
                ('firstName', models.CharField(max_length=35)),
                ('lastName', models.CharField(max_length=35)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('bio', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=100)),
                ('created_at', models.DateField()),
            ],
        ),
    ]
