# Generated by Django 4.1.6 on 2023-02-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupId', models.BigIntegerField()),
                ('userId', models.BigIntegerField()),
                ('comment', models.CharField(max_length=500)),
                ('createdAt', models.DateTimeField()),
            ],
        ),
    ]
