# Generated by Django 4.1.6 on 2023-02-23 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='groupId',
            new_name='group_id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='userId',
            new_name='user_id',
        ),
    ]
